### ISSUE TITLE
ValueError in break_timeline_attention

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-UMD/Rockwell#202]
```
INFO:werkzeug:127.0.0.1 - - [14/Jul/2023 10:12:17] "GET /hometimeline?worker_id=u3aCRluGVl&max_id=1679853216727433217&collection_started=2023-07-13T13:28:52&file_number=22 HTTP/1.1" 500 -
Traceback (most recent call last):                                                            
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)                                                                                                                                           
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)                                                       
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()                                                   
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)                                                        
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()                                                              
  File "/home/rockwell/miniconda3/envs/rockwell_deploy/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                                                
  File "/home/rockwell/Rockwell/backend/src/authorizer/twauth-web-v2.py", line 1054, in get_hometimeline    
    db_tweet_chronological_payload,db_tweet_chronological_attn_payload = break_timeline_attention(feed_tweets_chronological,feed_tweets_chronological_score,absent_tweets,max_pages)
  File "/home/rockwell/Rockwell/backend/src/authorizer/twauth-web-v2.py", line 198, in break_timeline_attention
    absent_tweets_select = np.random.choice(absent_tweets_ids,size=2,replace=False)                                                                                                         
  File "mtrand.pyx", line 934, in numpy.random.mtrand.RandomState.choice                                                                                                                    
ValueError: 'a' cannot be empty unless no samples are taken 
```

**Comment by saumyabhadani95** [comment]
Removed break_timeline_attention for now since it's not needed for endless feed. Will revisit this once if we need attention checks in the main experiment.

**Comment by glciampaglia** [comment]
We are not going to do attention checks anymore, moving to utopia and archiving.
